baseurl = "https://alessandro.bagno.li/"
title = "Alessandro Bagnoli"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
enableEmoji = true
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Alessandro Bagnoli"
  info = "Backend Engineer"
  description = "Alessandro Bagnoli's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/propic_square.jpg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/AlessandroBagnoli"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/alessandro-bagnoli/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/AlessandroBagRN"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 4
  url = "https://instagram.com/ale.bagnoli/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 5
  url = "https://t.me/AlessandroBagnoli"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 6
  url = "https://facebook.com/alessandro.bagnoli93/"
[[params.social]]
  name = "E-mail"
  icon = "fa fa-email-bulk-o fa-2x"
  weight = 7
  url = "mailto:alessandro@bagno.li"

# Menu links
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"